Fix missing payload for creating a release/tag Fix naming convention for GH runners Add a runtime analyzer for all runners Update CHANGELOG in release

diff --git a/.github/workflows/rust.yaml b/.github/workflows/rust.yaml
--- a/.github/workflows/rust.yaml
+++ b/.github/workflows/rust.yaml
@@ -18,6 +18,7 @@ jobs:
       contents: write
     outputs:
       release-id: ${{ steps.create-release.outputs.release_id }}
+      release-tag: ${{ steps.create-release.outputs.release_tag }}
       release-flag: ${{ steps.set-release-flag.outputs.release }}
       pkg-name: ${{ steps.get-package-info.outputs.pkg_name }}
       bin-name: ${{ steps.get-package-info.outputs.bin_name }}
@@ -67,8 +68,12 @@ jobs:
           done
 
           echo "Release Tag: ${{ env.pkg_version }}"
-          commit_msg="[${{ env.pkg_version }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
-          release_data="{\"tag_name\":\"$release_tag\",\"name\":\"$release_tag\",\"body\":\"$commit_msg\",\"draft\":false,\"prerelease\":$prerelease}"
+          latest_tag=$(git tag --list | sort -V | tail -n 1)
+          if [ -z "$latest_tag" ]; then
+            lastest_tag=$(curl -s -L https://api.github.com/repos/thevickypedia/lists3/releases/latest | jq -r .tag_name)  
+          fi
+          commit_msg="**Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/$lastest_tag...${{ env.pkg_version }}"
+          release_data="{\"tag_name\":\"${{ env.pkg_version }}\",\"name\":\"${{ env.pkg_version }}\",\"body\":\"$commit_msg\",\"draft\":false,\"prerelease\":$prerelease}"
           echo "Payload: $release_data"
           response=$(curl -X POST -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
             -d "$release_data" \
@@ -82,6 +87,7 @@ jobs:
           fi
           echo "Release ID: $release_id"
           echo "release_id=$release_id" >> "$GITHUB_OUTPUT"
+          echo "release_tag=${{ env.pkg_version }}" >> "$GITHUB_OUTPUT"
         shell: bash
 
   upload_assets:
@@ -90,7 +96,7 @@ jobs:
       matrix:
         platform:
           - release_for: Linux-x86_64
-            os: ubuntu-amd64
+            os: linux-amd64
             bin: ${{ needs.release.outputs.bin-name }}
             name: ${{ needs.release.outputs.pkg-name }}-linux-amd64.tar.gz
 
@@ -115,6 +121,16 @@ jobs:
     permissions:
       contents: write
     steps:
+      - name: Release ID Propagation
+        run: |
+          if [ -n "${{ needs.release.outputs.release-id }}" ]; then
+            echo "Release ID propagated: ${{ needs.release.outputs.release-id }}"
+          else
+            echo "Release ID propagation failed. Exiting.."
+            exit 1
+          fi
+          echo "start_time=$(date +%s)" >> "$GITHUB_ENV"
+        shell: bash
       - name: Checkout Repo
         uses: actions/checkout@v4
       - name: Update Rust
@@ -127,10 +143,11 @@ jobs:
           printf '*%.0s' {1..60} && printf "\n"
           echo "Updated rust version: $(rustc --version)"
           printf '*%.0s' {1..60} && printf "\n"
+        shell: bash
 
       - name: Install OpenSSL static for Windows
         # https://github.com/sfackler/rust-openssl/issues/1086
-        if: ${{ matrix.platform.os == 'windows-latest' }}
+        if: startsWith(matrix.platform.os, 'windows')
         run: |
           mkdir \Tools
           cd \Tools
@@ -139,6 +156,7 @@ jobs:
           echo ("vcpkg_dir=" + $pwd) >> $env:GITHUB_ENV
           .\bootstrap-vcpkg.bat
           .\vcpkg.exe install openssl:x64-windows-static
+        shell: pwsh
 
       - name: Build
         run: |
@@ -152,18 +170,20 @@ jobs:
         shell: bash
 
       - name: Copy Artifacts (Windows)
-        if: ${{ matrix.platform.os == 'windows-latest' }}
+        if: startsWith(matrix.platform.os, 'windows')
         run: |
           mkdir -p ${{ needs.release.outputs.pkg-name }}
           cp target/release/${{ matrix.platform.bin }} ${{ needs.release.outputs.pkg-name }}/${{ matrix.platform.bin }}
           Compress-Archive -DestinationPath ${{ matrix.platform.name }} -Path ${{ needs.release.outputs.pkg-name }}/
+        shell: pwsh
 
       - name: Copy Artifacts (macOS/Ubuntu)
-        if: ${{ matrix.platform.os != 'windows-latest' }}
+        if: "!startsWith(matrix.platform.os, 'windows')"
         run: |
           mkdir -p ${{ needs.release.outputs.pkg-name }}
           cp target/release/${{ matrix.platform.bin }} ${{ needs.release.outputs.pkg-name }}/${{ matrix.platform.bin }}
           tar -zcvf ${{ matrix.platform.name }} ${{ needs.release.outputs.pkg-name }}/
+        shell: bash
 
       - name: Upload Asset to Release
         run: |
@@ -171,4 +191,14 @@ jobs:
           -H "Content-Type: application/octet-stream" \
           --data-binary @"${{ matrix.platform.name }}" \
           "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.release.outputs.release-id }}/assets?name=${{ matrix.platform.name }}"
+        shell: bash
+
+      - name: Runtime Analyzer
+        run: |
+          start=${{ env.start_time }}
+          end=$(date +%s)
+          time_taken=$((end-start))
+          url="${{ github.server_url }}/${{ github.repository }}/releases/download/${{ needs.release.outputs.release-tag }}/${{ matrix.platform.name }}"
+          hyperlink="[${{ matrix.platform.release_for }}]($url)"
+          echo "🚀 Built for $hyperlink in $time_taken seconds" >> $GITHUB_STEP_SUMMARY
         shell: bash
